tunnel: YOUR_TUNNEL_ID
credentials-file: C:\Users\%USERNAME%\.cloudflared\YOUR_TUNNEL_ID.json

ingress:
  - hostname: harvest-db.yourdomain.com
    service: tcp://localhost:5432
  - service: http_status:404