services:
  - type: web
    name: harvest-messenger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://username:password@your-ngrok-url:5432/harvest_db
      - key: FLASK_ENV
        value: production