services:
  - type: web
    name: harvestano
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: harvestano-db
          property: connectionString

databases:
  - name: harvestano-db
    plan: free 