services:
  - type: web
    name: harvest-messenger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7293066749:AAFg5fXAVZkPx6s7R3drwGEV5pjKZY1f-PM
      - key: TELEGRAM_CHAT_ID
        value: "564049757"